const jCategory = [
    {
        index: 0,
        image: "images/google.png",
        title: "Web Developer",
        rate: '$900-$1200/m',
        av: "Full Time", 
        companyName: "Google",
        location: "USA",
        vacancy: "1",
        hours: "50hr / Week",
        description: "Google is seeking a talented Web Developer to join our team. This position is remote, offering you the flexibility to work from home while contributing to exciting, innovative projects. As a Web Developer, you will be responsible for designing, developing, and maintaining dynamic websites and web applications that align with the company’s standards of excellence.",
        workplace: "Work from Home",
        education: "Bachelor degree in any Computer Science Course",
        experience: "2 to 5 years",
    },
    {
        index: 1,
        image: "images/uber.png",
        title: "Freelancer",
        rate: "$900-$1200/m",
        av: "Part Time",
        companyName: "Uber",
        location: "USA",
        vacancy: "4",
        hours: "40hr / Week",
        description: "Uber is looking for talented freelancers to work on a variety of projects ranging from operational support to data analysis and creative problem-solving. This is a flexible, part-time role ideal for individuals who thrive in a dynamic, fast-paced environment while enjoying the freedom of freelancing.",
        workplace: "Remote with optional in-office collaboration",
        education: "Bachelor's degree in any field or equivalent practical experience",
        experience: "1 to 3 year(s) of relevant work experience, preferably in operations, analysis, or freelance projects",
    },


    {
        index: 2,
        image: "images/linkedin.png",
        title: "Business Associate",
        rate: "$900-$1200/m",
        av: "Part Time",
        companyName: "LinkedIn",
        location: "USA",
        vacancy: "2",
        hours: "30hr / Week",
        description: "LinkedIn is seeking a motivated Business Associate to support our business operations and strategic initiatives. This role is part-time and ideal for individuals with strong analytical skills, excellent communication abilities, and a passion for driving impactful results.",
        workplace: "Remote with occasional meetings",
        education: "Bachelor’s degree in Business Administration, Marketing, or a related field",
        experience: "1 to 2 years of experience in business operations or sales support",
    },
    {
        index: 3,
        image: "images/facebook.png",
        title: "Digital Marketing",
        rate: "$900-$1200/m",
        av: "Full Time",
        companyName: "Facebook",
        location: "USA",
        vacancy: "3",
        hours: "40hr / Week",
        description: "Join Facebook's dynamic marketing team as a Digital Marketer. You'll be responsible for creating and executing digital campaigns, analyzing performance metrics, and optimizing content to enhance brand presence and engagement.",
        workplace: "In-office or hybrid option",
        education: "Bachelor’s degree in Marketing, Communications, or a related field",
        experience: "2 to 4 years of experience in digital marketing, with a proven track record in SEO, SEM, and social media management",
    },
    {
        index: 4,
        image: "images/yahoo.png",
        title: "User Experience Designer",
        rate: "$900-$1200/m",
        av: "Full Time",
        companyName: "Yahoo",
        location: "USA",
        vacancy: "1",
        hours: "40hr / Week",
        description: "Yahoo is looking for a User Experience (UX) Designer to join our creative team. As a UX Designer, you will create intuitive, visually compelling designs for our digital platforms to improve user interaction and satisfaction.",
        workplace: "In-office with flexible work-from-home options",
        education: "Bachelor’s degree in Graphic Design, Human-Computer Interaction, or a related field",
        experience: "3 to 5 years of experience in UX design, with a strong portfolio showcasing web and mobile application projects",
    }


];